return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	-- build = ":TSUpdate",
	-- event = { "BufReadPost", "BufNewFile" },
	-- dependencies = {
	-- 	"nvim-treesitter/nvim-treesitter-textobjects",
	-- },
	-- cmd = { "TSUpdateSync" },
	-- keys = {
	-- 	{ "<c-space>", desc = "Increment selection" },
	-- 	{ "<bs>", desc = "Decrement selection", mode = "x" },
	-- },
	opts = {
		auto_install = true,
		highlight = { enable = true },
		indent = {
			enable = true,
		},
		autopairs = {
			enable = true,
		},
		autotag = {
			enable = false,
		},
		endwise = {
			enable = true,
		},
		ensure_installed = {
			"bash",
			"c",
			"html",
			"javascript",
			"java",
			"jsdoc",
			"json",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"python",
			"query",
			"regex",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
			"gleam",
			"kotlin",
			"go",
			"haskell",
		},
		-- incremental_selection = {
		-- 	enable = true,
		-- 	keymaps = {
		-- 		init_selection = "<C-space>",
		-- 		node_incremental = "<C-space>",
		-- 		scope_incremental = false,
		-- 		node_decremental = "<bs>",
		-- 	},
		-- },
	},
}
